# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import forge_plugin_v1_pb2 as forge__plugin__v1__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in forge_plugin_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForgePluginStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/forge.plugin.v1.ForgePlugin/Register',
                request_serializer=forge__plugin__v1__pb2.RegisterRequest.SerializeToString,
                response_deserializer=forge__plugin__v1__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/forge.plugin.v1.ForgePlugin/Invoke',
                request_serializer=forge__plugin__v1__pb2.InvokeRequest.SerializeToString,
                response_deserializer=forge__plugin__v1__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/forge.plugin.v1.ForgePlugin/HealthCheck',
                request_serializer=forge__plugin__v1__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=forge__plugin__v1__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Drain = channel.unary_unary(
                '/forge.plugin.v1.ForgePlugin/Drain',
                request_serializer=forge__plugin__v1__pb2.DrainRequest.SerializeToString,
                response_deserializer=forge__plugin__v1__pb2.DrainResponse.FromString,
                _registered_method=True)


class ForgePluginServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForgePluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=forge__plugin__v1__pb2.RegisterRequest.FromString,
                    response_serializer=forge__plugin__v1__pb2.RegisterResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=forge__plugin__v1__pb2.InvokeRequest.FromString,
                    response_serializer=forge__plugin__v1__pb2.InvokeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=forge__plugin__v1__pb2.HealthCheckRequest.FromString,
                    response_serializer=forge__plugin__v1__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=forge__plugin__v1__pb2.DrainRequest.FromString,
                    response_serializer=forge__plugin__v1__pb2.DrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forge.plugin.v1.ForgePlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forge.plugin.v1.ForgePlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForgePlugin:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.plugin.v1.ForgePlugin/Register',
            forge__plugin__v1__pb2.RegisterRequest.SerializeToString,
            forge__plugin__v1__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.plugin.v1.ForgePlugin/Invoke',
            forge__plugin__v1__pb2.InvokeRequest.SerializeToString,
            forge__plugin__v1__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.plugin.v1.ForgePlugin/HealthCheck',
            forge__plugin__v1__pb2.HealthCheckRequest.SerializeToString,
            forge__plugin__v1__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.plugin.v1.ForgePlugin/Drain',
            forge__plugin__v1__pb2.DrainRequest.SerializeToString,
            forge__plugin__v1__pb2.DrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
